CREATE TABLE USERS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '사용자 PK',
    LOGIN_ID VARCHAR(50) DEFAULT NULL COMMENT '일반 로그인 아이디',
    PASSWORD_HASH VARCHAR(255) DEFAULT NULL COMMENT '일반 로그인 비밀번호 해시',
    NAME VARCHAR(100) NOT NULL COMMENT '사용자 이름',
    USER_TYPE VARCHAR(30) NOT NULL DEFAULT 'STAFF' COMMENT '사용자 유형(OWNER, STAFF)',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '계정 상태(ACTIVE, INACTIVE, LOCKED)',
    PROFILE_INITIAL VARCHAR(2) NOT NULL DEFAULT '?' COMMENT '프로필 이니셜',
    PROFILE_COLOR VARCHAR(7) NOT NULL DEFAULT '#3B82F6' COMMENT '프로필 색상(#RRGGBB)',
    LAST_LOGIN_AT DATETIME DEFAULT NULL COMMENT '마지막 로그인 일시',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_USERS_LOGIN_ID (LOGIN_ID),
    KEY IDX_USERS_USER_TYPE (USER_TYPE),
    KEY IDX_USERS_STATUS (STATUS)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='회원 및 로그인 정보';

CREATE TABLE USER_SOCIAL_ACCOUNTS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '소셜 계정 연결 PK',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    PROVIDER VARCHAR(30) NOT NULL COMMENT '소셜 제공자(KAKAO, APPLE, GOOGLE)',
    PROVIDER_USER_ID VARCHAR(191) NOT NULL COMMENT '소셜 제공자의 사용자 고유 ID',
    PROVIDER_EMAIL VARCHAR(255) DEFAULT NULL COMMENT '소셜 제공자 이메일',
    PROVIDER_NAME VARCHAR(100) DEFAULT NULL COMMENT '소셜 제공자 이름',
    ACCESS_TOKEN VARCHAR(1000) DEFAULT NULL COMMENT '소셜 액세스 토큰(필요 시만 저장)',
    REFRESH_TOKEN VARCHAR(1000) DEFAULT NULL COMMENT '소셜 리프레시 토큰(필요 시만 저장)',
    TOKEN_EXPIRES_AT DATETIME DEFAULT NULL COMMENT '토큰 만료 일시',
    CONNECTED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '연결일시',
    LAST_LOGIN_AT DATETIME DEFAULT NULL COMMENT '해당 소셜 계정 마지막 로그인 일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_USER_SOCIAL_PROVIDER_USER (PROVIDER, PROVIDER_USER_ID),
    KEY IDX_USER_SOCIAL_USER_ID (USER_ID),
    KEY IDX_USER_SOCIAL_PROVIDER_EMAIL (PROVIDER_EMAIL)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='사용자 소셜 로그인 연결 정보';

CREATE TABLE WORKPLACES (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '사업장 PK',
    OWNER_ID BIGINT UNSIGNED NOT NULL COMMENT '사업장 소유자 사용자 ID',
    NAME VARCHAR(150) NOT NULL COMMENT '사업장명',
    ADDRESS VARCHAR(255) DEFAULT NULL COMMENT '사업장 주소',
    INVITE_CODE VARCHAR(20) NOT NULL COMMENT '사업장 초대코드',
    LATITUDE DECIMAL(10,7) DEFAULT NULL COMMENT '사업장 기준 위도',
    LONGITUDE DECIMAL(10,7) DEFAULT NULL COMMENT '사업장 기준 경도',
    ALLOWED_RADIUS_METERS INT UNSIGNED NOT NULL DEFAULT 100 COMMENT '출퇴근 허용 반경(m)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_WORKPLACES_INVITE_CODE (INVITE_CODE),
    KEY IDX_WORKPLACES_OWNER_ID (OWNER_ID)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='사업장 정보';

CREATE TABLE WORKPLACE_MEMBERS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '사업장 멤버 PK',
    WORKPLACE_ID BIGINT UNSIGNED NOT NULL COMMENT '사업장 ID',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    ROLE VARCHAR(30) NOT NULL COMMENT '사업장 내 역할(OWNER, MANAGER, STAFF)',
    HOURLY_WAGE DECIMAL(10,2) DEFAULT NULL COMMENT '시급',
    JOINED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '합류일시',
    STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' COMMENT '소속 상태(ACTIVE, INVITED, INACTIVE)',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_WORKPLACE_MEMBERS_WORKPLACE_USER (WORKPLACE_ID, USER_ID),
    KEY IDX_WORKPLACE_MEMBERS_USER_ID (USER_ID),
    KEY IDX_WORKPLACE_MEMBERS_ROLE (ROLE),
    KEY IDX_WORKPLACE_MEMBERS_STATUS (STATUS)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='사업장 소속 사용자 및 권한 정보';

CREATE TABLE ATTENDANCE_RECORDS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '근태 기록 PK',
    WORKPLACE_ID BIGINT UNSIGNED NOT NULL COMMENT '사업장 ID',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    WORK_DATE DATE NOT NULL COMMENT '근무일',
    CHECK_IN_AT DATETIME DEFAULT NULL COMMENT '출근 시각',
    CHECK_OUT_AT DATETIME DEFAULT NULL COMMENT '퇴근 시각',
    STATUS VARCHAR(30) NOT NULL DEFAULT 'WORKING' COMMENT '근태 상태(WORKING, COMPLETED, LATE, ABSENT)',
    WORKED_MINUTES INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '총 근무 분',
    BASE_WAGE DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '기본 계산 급여',
    FINAL_WAGE DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '최종 급여',
    NOTE VARCHAR(500) DEFAULT NULL COMMENT '비고',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_ATTENDANCE_RECORDS_WORKPLACE_USER_WORKDATE (WORKPLACE_ID, USER_ID, WORK_DATE),
    KEY IDX_ATTENDANCE_RECORDS_USER_ID (USER_ID),
    KEY IDX_ATTENDANCE_RECORDS_WORK_DATE (WORK_DATE),
    KEY IDX_ATTENDANCE_RECORDS_STATUS (STATUS)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='출퇴근 및 근무시간 기록';

CREATE TABLE ATTENDANCE_REQUESTS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '근태 정정 요청 PK',
    ATTENDANCE_RECORD_ID BIGINT UNSIGNED NOT NULL COMMENT '대상 근태 기록 ID',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT '요청 사용자 ID',
    TYPE VARCHAR(30) NOT NULL COMMENT '요청 유형(CHECK_IN_EDIT, CHECK_OUT_EDIT, BOTH_EDIT)',
    REQUESTED_CHECK_IN_AT DATETIME DEFAULT NULL COMMENT '요청 출근 시각',
    REQUESTED_CHECK_OUT_AT DATETIME DEFAULT NULL COMMENT '요청 퇴근 시각',
    REASON VARCHAR(1000) DEFAULT NULL COMMENT '요청 사유',
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT '요청 상태(PENDING, APPROVED, REJECTED)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (ID),
    KEY IDX_ATTENDANCE_REQUESTS_RECORD_ID (ATTENDANCE_RECORD_ID),
    KEY IDX_ATTENDANCE_REQUESTS_USER_ID (USER_ID),
    KEY IDX_ATTENDANCE_REQUESTS_TYPE (TYPE),
    KEY IDX_ATTENDANCE_REQUESTS_STATUS (STATUS)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='근태 정정 요청';

CREATE TABLE WORKPLACE_SETTINGS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '사업장 설정 PK',
    WORKPLACE_ID BIGINT UNSIGNED NOT NULL COMMENT '사업장 ID',
    LATE_GRACE_MINUTES INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '지각 인정 유예 분',
    SALARY_CALC_UNIT VARCHAR(20) NOT NULL DEFAULT 'MINUTE' COMMENT '급여 계산 단위(MINUTE, 10MIN, HOUR)',
    ROUNDING_POLICY VARCHAR(30) NOT NULL DEFAULT 'NONE' COMMENT '반올림 정책(NONE, FLOOR, CEIL, ROUND)',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_WORKPLACE_SETTINGS_WORKPLACE_ID (WORKPLACE_ID)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='사업장별 근태/급여 계산 설정';

CREATE TABLE PUSH_TOKENS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Ǫ�� ��ū PK',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT '����� ID',
    PLATFORM VARCHAR(20) NOT NULL COMMENT '�÷���(IOS, ANDROID, WEB)',
    TOKEN VARCHAR(512) NOT NULL COMMENT 'Ǫ�� ��ū',
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Ȱ�� ����',
    LAST_SEEN_AT DATETIME DEFAULT NULL COMMENT '������ ���� �ð�',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '�����Ͻ�',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '�����Ͻ�',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PUSH_TOKENS_TOKEN (TOKEN),
    KEY IDX_PUSH_TOKENS_USER_ID (USER_ID),
    KEY IDX_PUSH_TOKENS_USER_ACTIVE (USER_ID, IS_ACTIVE)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='����� Ǫ�� ��ū';

ALTER TABLE WORKPLACE_SETTINGS
    ADD COLUMN DEFAULT_HOURLY_WAGE DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '����� �⺻ �ñ�';

ALTER TABLE USERS
    ADD COLUMN PROFILE_INITIAL VARCHAR(2) NOT NULL DEFAULT '?' COMMENT '������ �̴ϼ�',
    ADD COLUMN PROFILE_COLOR VARCHAR(7) NOT NULL DEFAULT '#3B82F6' COMMENT '������ ����(#RRGGBB)';
