CREATE TABLE USERS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '사용자 PK',
    LOGIN_ID VARCHAR(50) DEFAULT NULL COMMENT '일반 로그인 아이디',
    PASSWORD_HASH VARCHAR(255) DEFAULT NULL COMMENT '일반 로그인 비밀번호 해시',
    NAME VARCHAR(100) NOT NULL COMMENT '사용자 이름',
    USER_TYPE VARCHAR(30) NOT NULL DEFAULT 'STAFF' COMMENT '사용자 유형(OWNER, STAFF, PERSONAL)',
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '계정 상태(ACTIVE, INACTIVE, LOCKED)',
    PROFILE_INITIAL VARCHAR(2) NOT NULL DEFAULT '?' COMMENT '프로필 이니셜',
    PROFILE_COLOR VARCHAR(7) NOT NULL DEFAULT '#3B82F6' COMMENT '프로필 색상(#RRGGBB)',
    LAST_LOGIN_AT DATETIME DEFAULT NULL COMMENT '마지막 로그인 일시',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_USERS_LOGIN_ID (LOGIN_ID),
    KEY IDX_USERS_USER_TYPE (USER_TYPE),
    KEY IDX_USERS_STATUS (STATUS)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='회원 및 로그인 정보';

CREATE TABLE USER_SOCIAL_ACCOUNTS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '소셜 계정 연결 PK',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    PROVIDER VARCHAR(30) NOT NULL COMMENT '소셜 제공자(KAKAO, APPLE, GOOGLE)',
    PROVIDER_USER_ID VARCHAR(191) NOT NULL COMMENT '소셜 제공자의 사용자 고유 ID',
    PROVIDER_EMAIL VARCHAR(255) DEFAULT NULL COMMENT '소셜 제공자 이메일',
    PROVIDER_NAME VARCHAR(100) DEFAULT NULL COMMENT '소셜 제공자 이름',
    ACCESS_TOKEN VARCHAR(1000) DEFAULT NULL COMMENT '소셜 액세스 토큰(필요 시만 저장)',
    REFRESH_TOKEN VARCHAR(1000) DEFAULT NULL COMMENT '소셜 리프레시 토큰(필요 시만 저장)',
    TOKEN_EXPIRES_AT DATETIME DEFAULT NULL COMMENT '토큰 만료 일시',
    CONNECTED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '연결일시',
    LAST_LOGIN_AT DATETIME DEFAULT NULL COMMENT '해당 소셜 계정 마지막 로그인 일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_USER_SOCIAL_PROVIDER_USER (PROVIDER, PROVIDER_USER_ID),
    KEY IDX_USER_SOCIAL_USER_ID (USER_ID),
    KEY IDX_USER_SOCIAL_PROVIDER_EMAIL (PROVIDER_EMAIL)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='사용자 소셜 로그인 연결 정보';

CREATE TABLE WORKPLACES (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '사업장 PK',
    OWNER_ID BIGINT UNSIGNED NOT NULL COMMENT '사업장 소유자 사용자 ID',
    NAME VARCHAR(150) NOT NULL COMMENT '사업장명',
    ADDRESS VARCHAR(255) DEFAULT NULL COMMENT '사업장 주소',
    INVITE_CODE VARCHAR(20) NOT NULL COMMENT '사업장 초대코드',
    LATITUDE DECIMAL(10,7) DEFAULT NULL COMMENT '사업장 기준 위도',
    LONGITUDE DECIMAL(10,7) DEFAULT NULL COMMENT '사업장 기준 경도',
    ALLOWED_RADIUS_METERS INT UNSIGNED NOT NULL DEFAULT 100 COMMENT '출퇴근 허용 반경(m)',
    USE_LOCATION_RESTRICTION TINYINT(1) NOT NULL DEFAULT 0 COMMENT '위치 기반 출퇴근 제한 사용 여부',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_WORKPLACES_INVITE_CODE (INVITE_CODE),
    KEY IDX_WORKPLACES_OWNER_ID (OWNER_ID)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='사업장 정보';

ALTER TABLE WORKPLACES
    ADD COLUMN IS_PERSONAL TINYINT(1) NOT NULL DEFAULT 0 COMMENT '개인 모드 사업장 여부';

CREATE TABLE WORKPLACE_MEMBERS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '사업장 멤버 PK',
    WORKPLACE_ID BIGINT UNSIGNED NOT NULL COMMENT '사업장 ID',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    ROLE VARCHAR(30) NOT NULL COMMENT '사업장 내 역할(OWNER, MANAGER, STAFF)',
    HOURLY_WAGE DECIMAL(10,2) DEFAULT NULL COMMENT '시급',
    JOINED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '합류일시',
    STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE' COMMENT '소속 상태(ACTIVE, INVITED, INACTIVE)',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_WORKPLACE_MEMBERS_WORKPLACE_USER (WORKPLACE_ID, USER_ID),
    KEY IDX_WORKPLACE_MEMBERS_USER_ID (USER_ID),
    KEY IDX_WORKPLACE_MEMBERS_ROLE (ROLE),
    KEY IDX_WORKPLACE_MEMBERS_STATUS (STATUS)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='사업장 소속 사용자 및 권한 정보';

ALTER TABLE WORKPLACE_MEMBERS
ADD COLUMN RECEIVE_ATTENDANCE_PUSH TINYINT(1) NOT NULL DEFAULT 1 COMMENT '직원 출퇴근 푸시 수신 여부';

CREATE TABLE ATTENDANCE_RECORDS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '근태 기록 PK',
    WORKPLACE_ID BIGINT UNSIGNED NOT NULL COMMENT '사업장 ID',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    WORK_DATE DATE NOT NULL COMMENT '근무일',
    CHECK_IN_AT DATETIME DEFAULT NULL COMMENT '출근 시각',
    CHECK_OUT_AT DATETIME DEFAULT NULL COMMENT '퇴근 시각',
    STATUS VARCHAR(30) NOT NULL DEFAULT 'WORKING' COMMENT '근태 상태(WORKING, COMPLETED, LATE, ABSENT)',
    WORKED_MINUTES INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '총 근무 분',
    BASE_WAGE DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '기본 계산 급여',
    FINAL_WAGE DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '최종 급여',
    NOTE VARCHAR(500) DEFAULT NULL COMMENT '비고',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_ATTENDANCE_RECORDS_WORKPLACE_USER_WORKDATE (WORKPLACE_ID, USER_ID, WORK_DATE),
    KEY IDX_ATTENDANCE_RECORDS_USER_ID (USER_ID),
    KEY IDX_ATTENDANCE_RECORDS_WORK_DATE (WORK_DATE),
    KEY IDX_ATTENDANCE_RECORDS_STATUS (STATUS)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='출퇴근 및 근무시간 기록';

CREATE TABLE ATTENDANCE_REQUESTS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '근태 정정 요청 PK',
    ATTENDANCE_RECORD_ID BIGINT UNSIGNED NOT NULL COMMENT '대상 근태 기록 ID',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT '요청 사용자 ID',
    TYPE VARCHAR(30) NOT NULL COMMENT '요청 유형(CHECK_IN_EDIT, CHECK_OUT_EDIT, BOTH_EDIT)',
    REQUESTED_CHECK_IN_AT DATETIME DEFAULT NULL COMMENT '요청 출근 시각',
    REQUESTED_CHECK_OUT_AT DATETIME DEFAULT NULL COMMENT '요청 퇴근 시각',
    REASON VARCHAR(1000) DEFAULT NULL COMMENT '요청 사유',
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING' COMMENT '요청 상태(PENDING, APPROVED, REJECTED)',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (ID),
    KEY IDX_ATTENDANCE_REQUESTS_RECORD_ID (ATTENDANCE_RECORD_ID),
    KEY IDX_ATTENDANCE_REQUESTS_USER_ID (USER_ID),
    KEY IDX_ATTENDANCE_REQUESTS_TYPE (TYPE),
    KEY IDX_ATTENDANCE_REQUESTS_STATUS (STATUS)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='근태 정정 요청';

CREATE TABLE WORKPLACE_SETTINGS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '사업장 설정 PK',
    WORKPLACE_ID BIGINT UNSIGNED NOT NULL COMMENT '사업장 ID',
    LATE_GRACE_MINUTES INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '지각 인정 유예 분',
    SALARY_CALC_UNIT VARCHAR(20) NOT NULL DEFAULT '10MIN' COMMENT '급여 계산 단위(MINUTE, 10MIN, HOUR)',
    ROUNDING_POLICY VARCHAR(30) NOT NULL DEFAULT 'NONE' COMMENT '반올림 정책(NONE, FLOOR, CEIL, ROUND)',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_WORKPLACE_SETTINGS_WORKPLACE_ID (WORKPLACE_ID)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='사업장별 근태/급여 계산 설정';

ALTER TABLE WORKPLACE_SETTINGS
    ADD COLUMN USE_BREAK_POLICY TINYINT(1) DEFAULT 0 NOT NULL COMMENT '휴게시간 정책 사용 여부';

CREATE TABLE PUSH_TOKENS (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '푸시 토큰 PK',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT '사용자 ID',
    PLATFORM VARCHAR(20) NOT NULL COMMENT '플랫폼(IOS, ANDROID, WEB)',
    TOKEN VARCHAR(512) NOT NULL COMMENT '푸시 토큰',
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1 COMMENT '활성 여부',
    LAST_SEEN_AT DATETIME DEFAULT NULL COMMENT '마지막 확인 시각',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PUSH_TOKENS_TOKEN (TOKEN),
    KEY IDX_PUSH_TOKENS_USER_ID (USER_ID),
    KEY IDX_PUSH_TOKENS_USER_ACTIVE (USER_ID, IS_ACTIVE)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='사용자별 푸시 토큰';

ALTER TABLE WORKPLACE_SETTINGS
    ADD COLUMN DEFAULT_HOURLY_WAGE DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '사업장 기본 시급';

ALTER TABLE WORKPLACE_SETTINGS
    ADD COLUMN DEFAULT_CHECK_IN_TIME TIME NULL COMMENT '기본 출근 시간',
    ADD COLUMN DEFAULT_CHECK_OUT_TIME TIME NULL COMMENT '기본 퇴근 시간';

CREATE TABLE WORKPLACE_BREAK_POLICIES
(
    ID               BIGINT UNSIGNED AUTO_INCREMENT COMMENT '휴게시간 정책 PK'
        PRIMARY KEY,
    WORKPLACE_ID     BIGINT UNSIGNED                      NOT NULL COMMENT '사업장 ID',
    NAME             VARCHAR(100)                         NOT NULL COMMENT '휴게시간 정책명',
    BREAK_TYPE       VARCHAR(20)                          NOT NULL COMMENT '휴게 유형(AUTO: 자동 차감, FIXED: 고정 휴게)',
    MIN_WORK_MINUTES INT UNSIGNED                         NULL COMMENT '최소 근무시간(분)',
    BREAK_MINUTES    INT UNSIGNED                         NOT NULL COMMENT '휴게시간(분)',
    IS_PAID          TINYINT(1) DEFAULT 0                 NOT NULL COMMENT '유급 휴게 여부',
    IS_ACTIVE        TINYINT(1) DEFAULT 1                 NOT NULL COMMENT '사용 여부',
    CREATED_AT       TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '생성일시',
    UPDATED_AT       TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '수정일시',
    CONSTRAINT FK_WORKPLACE_BREAK_POLICIES_WORKPLACE_ID
        FOREIGN KEY (WORKPLACE_ID) REFERENCES WORKPLACES (ID)
)
    COMMENT '사업장별 휴게시간 정책' CHARSET = UTF8MB4;

ALTER TABLE USERS
    ADD COLUMN PROFILE_INITIAL VARCHAR(2) NOT NULL DEFAULT '?' COMMENT '프로필 이니셜',
    ADD COLUMN PROFILE_COLOR VARCHAR(7) NOT NULL DEFAULT '#3B82F6' COMMENT '프로필 색상(#RRGGBB)';

ALTER TABLE WORKPLACE_MEMBERS
    ADD COLUMN MEMO VARCHAR(1000) DEFAULT NULL COMMENT '직원 메모';

CREATE TABLE PASSWORD_RESET_CODES (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Password reset code PK',
    USER_ID BIGINT UNSIGNED NOT NULL COMMENT 'Target user ID',
    EMAIL VARCHAR(191) NOT NULL COMMENT 'Recipient email',
    CODE VARCHAR(6) NOT NULL COMMENT '6-digit reset code',
    EXPIRES_AT DATETIME NOT NULL COMMENT 'Code expiration time',
    USED_AT DATETIME DEFAULT NULL COMMENT 'Code used time',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    PRIMARY KEY (ID),
    KEY IDX_PASSWORD_RESET_CODES_USER_ID (USER_ID),
    KEY IDX_PASSWORD_RESET_CODES_CODE (CODE),
    KEY IDX_PASSWORD_RESET_CODES_EXPIRES_AT (EXPIRES_AT)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='Password reset verification codes';

CREATE TABLE NOTICES (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Notice PK',
    TITLE VARCHAR(200) NOT NULL COMMENT 'Notice title',
    CONTENT VARCHAR(5000) NOT NULL COMMENT 'Notice content',
    IS_PINNED TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Pinned flag',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created at',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated at',
    PRIMARY KEY (ID),
    KEY IDX_NOTICES_PINNED_CREATED_AT (IS_PINNED, CREATED_AT),
    KEY IDX_NOTICES_CREATED_AT (CREATED_AT)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='Global notices';

CREATE TABLE TERMS (
    ID           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '약관 PK',
    TERMS_TYPE   VARCHAR(30)     NOT NULL                COMMENT '약관 유형(TERMS_OF_SERVICE, PRIVACY_POLICY)',
    VERSION      VARCHAR(10)     NOT NULL                COMMENT '약관 버전(예: 1.0, 1.1)',
    TITLE        VARCHAR(200)    NOT NULL                COMMENT '약관 제목',
    CONTENT      LONGTEXT        NOT NULL                COMMENT '약관 본문',
    IS_REQUIRED  TINYINT(1)      NOT NULL DEFAULT 1      COMMENT '필수 동의 여부(1: 필수, 0: 선택)',
    IS_ACTIVE    TINYINT(1)      NOT NULL DEFAULT 0      COMMENT '현재 유효한 버전 여부(1: 활성, 0: 비활성)',
    EFFECTIVE_AT DATETIME        NOT NULL                COMMENT '약관 시행일',
    CREATED_AT   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_TERMS_TYPE_VERSION (TERMS_TYPE, VERSION),
    KEY IDX_TERMS_TYPE_ACTIVE (TERMS_TYPE, IS_ACTIVE)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='이용약관 및 개인정보처리방침 버전 관리';

-- 최고관리자: USER_TYPE에 'SUPER_ADMIN' 추가 및 계정 생성
ALTER TABLE USERS
    MODIFY COLUMN USER_TYPE VARCHAR(30) NOT NULL DEFAULT 'STAFF' COMMENT '사용자 유형(OWNER, STAFF, PERSONAL, SUPER_ADMIN)';

INSERT INTO USERS (LOGIN_ID, PASSWORD_HASH, NAME, USER_TYPE, STATUS, PROFILE_INITIAL, PROFILE_COLOR)
VALUES ('admin@codedream.co.kr', '$2b$10$nzicyOgXNW04tLaiWSCXGeZ94DtUhLCc4VPgEDYNSWZV3noT9i5BS', '최고관리자', 'SUPER_ADMIN', 'ACTIVE', '관', '#1D4ED8');

CREATE TABLE USER_WITHDRAWAL_REASONS (
    ID            BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '탈퇴 사유 PK',
    USER_ID       BIGINT UNSIGNED NOT NULL                COMMENT '탈퇴한 사용자 ID',
    REASON_TYPE   VARCHAR(50)     NOT NULL                COMMENT '탈퇴 사유 유형(NOT_USED_OFTEN, INCONVENIENT, PRIVACY_CONCERN, SWITCHING_SERVICE, WORKPLACE_CLOSED, OTHER)',
    CUSTOM_REASON VARCHAR(1000)   DEFAULT NULL            COMMENT '기타 직접 입력 사유',
    CREATED_AT    TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성일시',
    PRIMARY KEY (ID),
    KEY IDX_USER_WITHDRAWAL_REASONS_USER_ID (USER_ID),
    KEY IDX_USER_WITHDRAWAL_REASONS_REASON_TYPE (REASON_TYPE)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='회원 탈퇴 사유';

CREATE TABLE PAYSLIPS (
    ID               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '급여명세서 PK',
    WORKPLACE_ID     BIGINT UNSIGNED NOT NULL COMMENT '사업장 ID',
    USER_ID          BIGINT UNSIGNED NOT NULL COMMENT '직원 사용자 ID',
    FROM_DATE        DATE NOT NULL COMMENT '급여 기간 시작일',
    TO_DATE          DATE NOT NULL COMMENT '급여 기간 종료일',
    HOURLY_WAGE      DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '적용 시급(발행 시점 스냅샷)',
    WORKED_DAYS      INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '총 근무일수',
    WORKED_MINUTES   INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '총 근무시간(분)',
    BASE_WAGE        DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '기본 급여(근무 기준 계산)',
    BONUS_AMOUNT     DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '추가 지급액',
    BONUS_NOTE       VARCHAR(500) DEFAULT NULL COMMENT '추가 지급 사유',
    DEDUCTION_AMOUNT DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '공제액',
    DEDUCTION_NOTE   VARCHAR(500) DEFAULT NULL COMMENT '공제 사유',
    TOTAL_WAGE       DECIMAL(12,2) NOT NULL DEFAULT 0.00 COMMENT '최종 급여(기본 + 추가 - 공제)',
    DAILY_SNAPSHOT   LONGTEXT NOT NULL COMMENT '일별 근무 내역 스냅샷(JSON)',
    STATUS           VARCHAR(20) NOT NULL DEFAULT 'ISSUED' COMMENT '명세서 상태(ISSUED, CANCELLED)',
    CREATED_AT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '발행일시',
    UPDATED_AT       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    PRIMARY KEY (ID),
    KEY IDX_PAYSLIPS_WORKPLACE_ID (WORKPLACE_ID),
    KEY IDX_PAYSLIPS_USER_ID (USER_ID),
    KEY IDX_PAYSLIPS_FROM_DATE (FROM_DATE),
    KEY IDX_PAYSLIPS_STATUS (STATUS)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='급여 명세서';

CREATE TABLE USER_TERMS_AGREEMENTS (
    ID        BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '동의 이력 PK',
    USER_ID   BIGINT UNSIGNED NOT NULL                COMMENT '사용자 ID',
    TERMS_ID  BIGINT UNSIGNED NOT NULL                COMMENT '동의한 약관 ID',
    AGREED_AT TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '동의 일시',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_USER_TERMS_AGREEMENTS_USER_TERMS (USER_ID, TERMS_ID),
    KEY IDX_USER_TERMS_AGREEMENTS_USER_ID (USER_ID),
    KEY IDX_USER_TERMS_AGREEMENTS_TERMS_ID (TERMS_ID)
) ENGINE=INNODB
  DEFAULT CHARSET=UTF8MB4
  COLLATE=UTF8MB4_GENERAL_CI
  COMMENT='사용자 약관 동의 이력';
