package com.api.alba.email;

public class EmailForm {

    // 비밀번호 설정 인증 메일
    public static String getAuthContent() {
        return "<!DOCTYPE html>\n"
            + "<html lang=\"ko\">\n"
            + "  <head>\n"
            + "    <meta charset=\"UTF-8\" />\n"
            + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
            + "    <title>알밤 인증</title>\n"
            + "    <style>\n"
            + "      body {\n"
            + "        margin-top: 3rem;\n"
            + "        margin-bottom: 3rem;\n"
            + "      }\n"
            + "      hr {\n"
            + "        margin-top: 5px;\n"
            + "        margin-bottom: 20px;\n"
            + "      }\n"
            + "      .container {\n"
            + "        max-width: 650px;\n"
            + "        margin: 0px auto;\n"
            + "        padding: 3rem;\n"
            + "      }\n"
            + "      .title {\n"
            + "        font-size: 1.5rem;\n"
            + "        color: #555;\n"
            + "        text-align: left;\n"
            + "        font-weight: 600;\n"
            + "        line-height: 1.8;\n"
            + "      }\n"
            + "      .content {\n"
            + "        font-size: 1.25rem;\n"
            + "        color: #555;\n"
            + "        text-align: left;\n"
            + "        font-weight: 400;\n"
            + "        line-height: 1.8;\n"
            + "      }\n"
            + "      .box {\n"
            + "        margin-top: 1.5rem;\n"
            + "        border-radius: 0.5rem;\n"
            + "        padding: 3rem;\n"
            + "        background-color: rgb(248, 249, 250);\n"
            + "        color: rgba(33, 37, 41, 0.75);\n"
            + "      }\n"
            + "      .box span {\n"
            + "        color: #384B60;\n"
            + "        font-weight: 800;\n"
            + "      }\n"
            + "      .sign {\n"
            + "        margin-top: 2rem;\n"
            + "        text-align: center;\n"
            + "      }\n"
            + "    </style>\n"
            + "  </head>\n"
            + "  <body>\n"
            + "    <div class=\"container\">\n"
            + "      <div class=\"title\">\n"
            + "      비밀번호 재설정을 위한 인증코드입니다.\n"
            + "      </div>\n"
            + "      <hr />\n"
            + "      <div class=\"content\">\n"
            + "        안녕하세요. #{이름}님\n"
            + "        <br />\n"
            + "        아래 인증코드를 화면에 입력해 주세요.\n"
            + "      </div>\n"
            + "      <div class=\"box\">인증코드 : <span>#{인증코드}</span></div>\n"
            + "\n"
            + "      <p class=\"sign\">\n"
            + "        <img\n"
            + "          src=\"https://tistory1.daumcdn.net/tistory/2906470/skin/images/splash.png\"\n"
            + "          width=\"205px\"\n"
            + "          height=\"50px\"\n"
            + "          loading=\"lazy\"\n"
            + "        />\n"
            + "      </p>\n"
            + "    </div>\n"
            + "  </body>\n"
            + "</html>\n";
    }


}
